### ISSUE TITLE
访问ldap并没有获取到http协议下的badClassName

### ISSUE THREAD

**Issue by DH-Illidan** [EmYiQing/LDAPKit#3]
![image](https://user-images.githubusercontent.com/55729509/146324894-4a5018ff-e082-4595-a6f0-3473fc20f585.png)

只返回了引用类的信息, 却没有去http下获取badClassName类文件

**Comment by EmYiQing** [comment]
工具应该没有问题，经过了很多测试
你这个情况很可能是本地JDK版本的问题，比如JDK版本大于8u191是不可以LDAP加载类的，也有可能是其他原因
（另外这个工具暂时删除了，等风头过去再继续完善）
